// src/app/signup/brand/page.js (UX 개선 최종 버전)
'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { submitBrand } from '../../actions';
const sportsData = { 정회원: ["가라테","검도","게이트볼","골프","궁도","근대5종","농구","댄스스포츠","럭비","레슬링","롤러스포츠","루지","바이애슬론","바둑","배구","배드민턴","봅슬레이-스켈레톤","복싱","볼링","빙상","사격","산악","삼보","세팍타크로","소프트볼","수상스키-웨이크스포츠","수영","스키","스쿼시","승마","씨름","아이스하키","야구","양궁","역도","요트","우슈","유도","육상","정구","조정","족구","체조","축구","카누","컬링","탁구","태권도","테니스","트라이애슬론","펜싱","하키","핸드볼"], 준회원: ["라크로스","소프트테니스","스키점프","에어로빅","주짓수","카이트보딩","파크골프","플로어볼"], 인정단체: ["공수도","국무도","국학기공","무에타이","브리지","비치발리볼","스포츠줄다리기","이스포츠","줄넘기","체스","치어리딩","카바디","파워보트"] };
const productCategories = ["스포츠용품","음료","건강기능식품","생활용품","자동차","가구","여행사","온라인 쇼핑몰","패션"];
const FormSection = ({ title, description, children }) => (<div className="py-8 border-b border-border"><h2 className="text-xl font-bold text-primary">{title}</h2><p className="text-secondary mt-1 mb-6">{description}</p>{children}</div>);
const InputField = ({ label, ...props }) => (<div><label className="block mb-2 text-md font-bold text-primary">{label}</label><input {...props} className="w-full p-3 bg-white border border-border rounded-lg focus:ring-accent focus:border-accent" /></div>);
const TextareaField = ({ label, ...props }) => (<div><label className="block mb-2 text-md font-bold text-primary">{label}</label><textarea {...props} rows="3" className="w-full p-3 bg-white border border-border rounded-lg focus:ring-accent focus:border-accent" /></div>);
const CheckboxGrid = ({ items, onChange, selectedItems }) => (<div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">{items.map(item => (<label key={item} className="flex items-center space-x-3 p-3 rounded-lg hover:bg-gray-50 cursor-pointer"><input type="checkbox" className="w-5 h-5 text-accent rounded-md border-gray-300 focus:ring-accent" onChange={() => onChange(item)} checked={selectedItems.includes(item)} /><span className="text-primary font-medium">{item}</span></label>))}</div>);
export default function BrandSignUp() {
  const router = useRouter(); const [isSubmitting, setIsSubmitting] = useState(false); const [formData, setFormData] = useState({ name: '', category: productCategories[0], sports: [], contactName: '', contact: '', email: '', brandIntro: '', sponsorshipEffect: '', link: '' });
  const handleInputChange = (e) => { const { name, value } = e.target; setFormData(prev => ({ ...prev, [name]: value })); };
  const handleSportChange = (sport) => { setFormData(prev => ({ ...prev, sports: prev.sports.includes(sport) ? prev.sports.filter(s => s !== sport) : [...prev.sports, sport] })); };
  const handleSubmit = async (e) => { e.preventDefault(); setIsSubmitting(true); const result = await submitBrand(formData); if (result.success) { alert('후원 제안이 성공적으로 등록되었습니다!'); router.push('/admin'); } else { alert('등록 중 오류가 발생했습니다: ' + result.error); } setIsSubmitting(false); };
  return (<div className="max-w-3xl mx-auto"><div className="text-center mb-12"><h1 className="text-4xl font-bold mb-2">후원 파트너 제안하기</h1><p className="text-lg text-secondary">우리 브랜드를 알리고 멋진 파트너와 함께 성장하세요.</p></div><form onSubmit={handleSubmit} className="space-y-4">
    <FormSection title="1. 기본 정보" description="후원 제안 및 연락을 위해 필요한 정보입니다."><div className="space-y-6"><InputField label="브랜드명 / 제품명" name="name" value={formData.name} onChange={handleInputChange} /><InputField label="담당자 이름" name="contactName" value={formData.contactName} onChange={handleInputChange} /><InputField label="연락처" name="contact" value={formData.contact} onChange={handleInputChange} /><InputField label="이메일" name="email" type="email" value={formData.email} onChange={handleInputChange} /><div><label className="block mb-2 text-md font-bold text-primary">제품 카테고리</label><select name="category" value={formData.category} onChange={handleInputChange} className="w-full p-3 bg-white border border-border rounded-lg">{productCategories.map(cat => <option key={cat}>{cat}</option>)}</select></div></div></FormSection>
    <FormSection title="2. 선호 후원 종목" description="특별히 관심있는 종목이 있다면 모두 선택해주세요. (중복 가능)"><div className="space-y-6"><h3 className="font-bold text-md text-primary mb-3">정회원 종목</h3><CheckboxGrid items={sportsData.정회원} onChange={handleSportChange} selectedItems={formData.sports} /><h3 className="font-bold text-md text-primary mt-6 mb-3">준회원 종목</h3><CheckboxGrid items={sportsData.준회원} onChange={handleSportChange} selectedItems={formData.sports} /><h3 className="font-bold text-md text-primary mt-6 mb-3">인정 단체</h3><CheckboxGrid items={sportsData.인정단체} onChange={handleSportChange} selectedItems={formData.sports} /></div></FormSection>
    <FormSection title="3. 상세 프로필 (선택)" description="자세히 작성할수록 선수/팀이 브랜드를 더 잘 이해할 수 있습니다."><div className="space-y-6"><TextareaField label="브랜드 / 제품 소개" name="brandIntro" value={formData.brandIntro} onChange={handleInputChange} placeholder="예: 저희는 MZ세대를 위한 비건 에너지 드링크를 만드는 브랜드입니다. 선수들의 열정을 응원합니다." /><TextareaField label="후원을 통해 얻고 싶은 효과" name="sponsorshipEffect" value={formData.sponsorshipEffect} onChange={handleInputChange} placeholder="예: 열정적인 유망주 후원을 통해, 도전적인 브랜드 이미지를 구축하고 싶습니다." /><InputField label="홈페이지 / SNS 링크" name="link" type="url" value={formData.link} onChange={handleInputChange} placeholder="https://sponsorlink.com" /></div></FormSection>
    <div className="pt-10 text-center"><button type="submit" disabled={isSubmitting} className="w-full max-w-lg mx-auto block px-12 py-5 bg-blue-600 text-white rounded-lg text-xl font-bold hover:bg-blue-700 transition-colors shadow-lg disabled:bg-gray-400">{isSubmitting ? '등록 중...' : '후원 제안 등록하기'}</button></div>
  </form></div>);
}
