// src/app/signup/consumer/page.js (UX 개선 최종 버전)
'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { submitConsumer } from '../../actions';
const sportsData = { 정회원: ["가라테","검도","게이트볼","골프","궁도","근대5종","농구","댄스스포츠","럭비","레슬링","롤러스포츠","루지","바이애슬론","바둑","배구","배드민턴","봅슬레이-스켈레톤","복싱","볼링","빙상","사격","산악","삼보","세팍타크로","소프트볼","수상스키-웨이크스포츠","수영","스키","스쿼시","승마","씨름","아이스하키","야구","양궁","역도","요트","우슈","유도","육상","정구","조정","족구","체조","축구","카누","컬링","탁구","태권도","테니스","트라이애슬론","펜싱","하키","핸드볼"], 준회원: ["라크로스","소프트테니스","스키점프","에어로빅","주짓수","카이트보딩","파크골프","플로어볼"], 인정단체: ["공수도","국무도","국학기공","무에타이","브리지","비치발리볼","스포츠줄다리기","이스포츠","줄넘기","체스","치어리딩","카바디","파워보트"] };
const productCategories = ["스포츠용품","음료","건강기능식품","생활용품","자동차","가구","여행사","온라인 쇼핑몰","패션"];
const FormSection = ({ title, description, children }) => (<div className="py-8 border-b border-border"><h2 className="text-xl font-bold text-primary">{title}</h2><p className="text-secondary mt-1 mb-6">{description}</p>{children}</div>);
const InputField = ({ label, ...props }) => (<div><label className="block mb-2 text-md font-bold text-primary">{label}</label><input {...props} className="w-full p-3 bg-white border border-border rounded-lg focus:ring-accent focus:border-accent" /></div>);
const TextareaField = ({ label, ...props }) => (<div><label className="block mb-2 text-md font-bold text-primary">{label}</label><textarea {...props} rows="4" className="w-full p-3 bg-white border border-border rounded-lg focus:ring-accent focus:border-accent" /></div>);
const CheckboxGrid = ({ items, onChange, selectedItems }) => (<div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">{items.map(item => (<label key={item} className="flex items-center space-x-3 p-3 rounded-lg hover:bg-gray-50 cursor-pointer"><input type="checkbox" className="w-5 h-5 text-accent rounded-md border-gray-300 focus:ring-accent" onChange={() => onChange(item)} checked={selectedItems.includes(item)} /><span className="text-primary font-medium">{item}</span></label>))}</div>);
export default function ConsumerSignUp() {
  const router = useRouter(); const [isSubmitting, setIsSubmitting] = useState(false); const [formData, setFormData] = useState({ type: '선수', sport: '', categories: [], name: '', contact: '', email: '', intro: '', career: '', goal: '', link: '' });
  const handleInputChange = (e) => { const { name, value } = e.target; setFormData(prev => ({ ...prev, [name]: value })); };
  const handleCategoryChange = (category) => { setFormData(prev => { const newCategories = prev.categories.includes(category) ? prev.categories.filter(item => item !== category) : [...prev.categories, category]; if (newCategories.length > 3) { alert('희망 후원 카테고리는 최대 3개까지 선택할 수 있습니다.'); return prev; } return { ...prev, categories: newCategories }; }); };
  const handleSubmit = async (e) => { e.preventDefault(); setIsSubmitting(true); const result = await submitConsumer(formData); if (result.success) { alert('프로필이 성공적으로 등록되었습니다!'); router.push('/admin'); } else { alert('등록 중 오류가 발생했습니다: ' + result.error); } setIsSubmitting(false); };
  return (<div className="max-w-3xl mx-auto"><div className="text-center mb-12"><h1 className="text-4xl font-bold mb-2">후원 프로필 등록하기</h1><p className="text-lg text-secondary">나를 알리고 필요한 후원을 제안 받아보세요.</p></div><form onSubmit={handleSubmit} className="space-y-4">
    <FormSection title="1. 기본 정보" description="후원 계약 및 연락을 위해 필요한 정보입니다."><div className="space-y-6"><InputField label="담당자 이름" name="name" value={formData.name} onChange={handleInputChange} /><InputField label="연락처" name="contact" value={formData.contact} onChange={handleInputChange} placeholder="010-1234-5678" /><InputField label="이메일" name="email" type="email" value={formData.email} onChange={handleInputChange} placeholder="sponsor@link.com" /></div></FormSection>
    <FormSection title="2. 후원 희망 정보" description="이 정보를 바탕으로 최적의 후원사를 추천해 드립니다."><div className="space-y-8"><div><label className="block mb-2 text-md font-bold text-primary">가입 유형</label><select name="type" value={formData.type} onChange={handleInputChange} className="w-full p-3 bg-white border border-border rounded-lg"><option>선수</option><option>스포츠팀</option><option>종목 단체</option></select></div><div><label className="block mb-2 text-md font-bold text-primary">종목</label><select name="sport" value={formData.sport} onChange={handleInputChange} className="w-full p-3 bg-white border border-border rounded-lg"><option value="">-- 종목 선택 --</option><optgroup label="정회원 종목">{sportsData.정회원.map(s => <option key={s}>{s}</option>)}</optgroup><optgroup label="준회원 종목">{sportsData.준회원.map(s => <option key={s}>{s}</option>)}</optgroup><optgroup label="인정 단체">{sportsData.인정단체.map(s => <option key={s}>{s}</option>)}</optgroup></select></div><div><label className="block mb-2 text-md font-bold text-primary">희망 후원 카테고리 (최대 3개)</label><CheckboxGrid items={productCategories} onChange={handleCategoryChange} selectedItems={formData.categories} /></div></div></FormSection>
    <FormSection title="3. 상세 프로필 (선택)" description="자세히 작성할수록 매칭 확률이 올라갑니다!"><div className="space-y-6"><InputField label="한 줄 자기소개" name="intro" value={formData.intro} onChange={handleInputChange} placeholder="예: 대한민국을 빛낼 차세대 수영 국가대표" /><TextareaField label="주요 경력 / 수상 내역" name="career" value={formData.career} onChange={handleInputChange} placeholder="- 2024 전국체전 수영 100m 금메달&#10;- 2023 아시안게임 국가대표" /><TextareaField label="후원 목표 및 활용 계획" name="goal" value={formData.goal} onChange={handleInputChange} placeholder="후원금을 통해 해외 전지훈련 비용을 마련하여, 다음 올림픽에서 최고의 기량을 선보이고 싶습니다." /><InputField label="포트폴리오 / SNS 링크" name="link" type="url" value={formData.link} onChange={handleInputChange} placeholder="https://instagram.com/sponsorlink" /></div></FormSection>
    <div className="pt-10 text-center"><button type="submit" disabled={isSubmitting} className="w-full max-w-lg mx-auto block px-12 py-5 bg-blue-600 text-white rounded-lg text-xl font-bold hover:bg-blue-700 transition-colors shadow-lg disabled:bg-gray-400">{isSubmitting ? '등록 중...' : '내 프로필 등록하기'}</button></div>
  </form></div>);
}
